// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: controller.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WPIMath.Proto {

  /// <summary>Holder for reflection information generated from controller.proto</summary>
  public static partial class ControllerReflection {

    #region Descriptor
    /// <summary>File descriptor for controller.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ControllerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBjb250cm9sbGVyLnByb3RvEgl3cGkucHJvdG8iSAoWUHJvdG9idWZBcm1G",
            "ZWVkZm9yd2FyZBIKCgJrcxgBIAEoARIKCgJrZxgCIAEoARIKCgJrdhgDIAEo",
            "ARIKCgJrYRgEIAEoASJ0CiRQcm90b2J1ZkRpZmZlcmVudGlhbERyaXZlRmVl",
            "ZGZvcndhcmQSEQoJa3ZfbGluZWFyGAEgASgBEhEKCWthX2xpbmVhchgCIAEo",
            "ARISCgprdl9hbmd1bGFyGAMgASgBEhIKCmthX2FuZ3VsYXIYBCABKAEiTQob",
            "UHJvdG9idWZFbGV2YXRvckZlZWRmb3J3YXJkEgoKAmtzGAEgASgBEgoKAmtn",
            "GAIgASgBEgoKAmt2GAMgASgBEgoKAmthGAQgASgBIkQKHlByb3RvYnVmU2lt",
            "cGxlTW90b3JGZWVkZm9yd2FyZBIKCgJrcxgBIAEoARIKCgJrdhgCIAEoARIK",
            "CgJrYRgDIAEoASJFCiZQcm90b2J1ZkRpZmZlcmVudGlhbERyaXZlV2hlZWxW",
            "b2x0YWdlcxIMCgRsZWZ0GAEgASgBEg0KBXJpZ2h0GAIgASgBQioKGGVkdS53",
            "cGkuZmlyc3QubWF0aC5wcm90b6oCDVdQSU1hdGguUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufArmFeedforward), global::WPIMath.Proto.ProtobufArmFeedforward.Parser, new[]{ "Ks", "Kg", "Kv", "Ka" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufDifferentialDriveFeedforward), global::WPIMath.Proto.ProtobufDifferentialDriveFeedforward.Parser, new[]{ "KvLinear", "KaLinear", "KvAngular", "KaAngular" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufElevatorFeedforward), global::WPIMath.Proto.ProtobufElevatorFeedforward.Parser, new[]{ "Ks", "Kg", "Kv", "Ka" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufSimpleMotorFeedforward), global::WPIMath.Proto.ProtobufSimpleMotorFeedforward.Parser, new[]{ "Ks", "Kv", "Ka" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufDifferentialDriveWheelVoltages), global::WPIMath.Proto.ProtobufDifferentialDriveWheelVoltages.Parser, new[]{ "Left", "Right" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtobufArmFeedforward : pb::IMessage<ProtobufArmFeedforward>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufArmFeedforward> _parser = new pb::MessageParser<ProtobufArmFeedforward>(() => new ProtobufArmFeedforward());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufArmFeedforward> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.ControllerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufArmFeedforward() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufArmFeedforward(ProtobufArmFeedforward other) : this() {
      ks_ = other.ks_;
      kg_ = other.kg_;
      kv_ = other.kv_;
      ka_ = other.ka_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufArmFeedforward Clone() {
      return new ProtobufArmFeedforward(this);
    }

    /// <summary>Field number for the "ks" field.</summary>
    public const int KsFieldNumber = 1;
    private double ks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Ks {
      get { return ks_; }
      set {
        ks_ = value;
      }
    }

    /// <summary>Field number for the "kg" field.</summary>
    public const int KgFieldNumber = 2;
    private double kg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Kg {
      get { return kg_; }
      set {
        kg_ = value;
      }
    }

    /// <summary>Field number for the "kv" field.</summary>
    public const int KvFieldNumber = 3;
    private double kv_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Kv {
      get { return kv_; }
      set {
        kv_ = value;
      }
    }

    /// <summary>Field number for the "ka" field.</summary>
    public const int KaFieldNumber = 4;
    private double ka_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Ka {
      get { return ka_; }
      set {
        ka_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufArmFeedforward);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufArmFeedforward other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Ks, other.Ks)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Kg, other.Kg)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Kv, other.Kv)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Ka, other.Ka)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ks != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Ks);
      if (Kg != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Kg);
      if (Kv != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Kv);
      if (Ka != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Ka);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ks != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Ks);
      }
      if (Kg != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Kg);
      }
      if (Kv != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Kv);
      }
      if (Ka != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Ka);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ks != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Ks);
      }
      if (Kg != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Kg);
      }
      if (Kv != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Kv);
      }
      if (Ka != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Ka);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ks != 0D) {
        size += 1 + 8;
      }
      if (Kg != 0D) {
        size += 1 + 8;
      }
      if (Kv != 0D) {
        size += 1 + 8;
      }
      if (Ka != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufArmFeedforward other) {
      if (other == null) {
        return;
      }
      if (other.Ks != 0D) {
        Ks = other.Ks;
      }
      if (other.Kg != 0D) {
        Kg = other.Kg;
      }
      if (other.Kv != 0D) {
        Kv = other.Kv;
      }
      if (other.Ka != 0D) {
        Ka = other.Ka;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Ks = input.ReadDouble();
            break;
          }
          case 17: {
            Kg = input.ReadDouble();
            break;
          }
          case 25: {
            Kv = input.ReadDouble();
            break;
          }
          case 33: {
            Ka = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Ks = input.ReadDouble();
            break;
          }
          case 17: {
            Kg = input.ReadDouble();
            break;
          }
          case 25: {
            Kv = input.ReadDouble();
            break;
          }
          case 33: {
            Ka = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufDifferentialDriveFeedforward : pb::IMessage<ProtobufDifferentialDriveFeedforward>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufDifferentialDriveFeedforward> _parser = new pb::MessageParser<ProtobufDifferentialDriveFeedforward>(() => new ProtobufDifferentialDriveFeedforward());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufDifferentialDriveFeedforward> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.ControllerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveFeedforward() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveFeedforward(ProtobufDifferentialDriveFeedforward other) : this() {
      kvLinear_ = other.kvLinear_;
      kaLinear_ = other.kaLinear_;
      kvAngular_ = other.kvAngular_;
      kaAngular_ = other.kaAngular_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveFeedforward Clone() {
      return new ProtobufDifferentialDriveFeedforward(this);
    }

    /// <summary>Field number for the "kv_linear" field.</summary>
    public const int KvLinearFieldNumber = 1;
    private double kvLinear_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double KvLinear {
      get { return kvLinear_; }
      set {
        kvLinear_ = value;
      }
    }

    /// <summary>Field number for the "ka_linear" field.</summary>
    public const int KaLinearFieldNumber = 2;
    private double kaLinear_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double KaLinear {
      get { return kaLinear_; }
      set {
        kaLinear_ = value;
      }
    }

    /// <summary>Field number for the "kv_angular" field.</summary>
    public const int KvAngularFieldNumber = 3;
    private double kvAngular_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double KvAngular {
      get { return kvAngular_; }
      set {
        kvAngular_ = value;
      }
    }

    /// <summary>Field number for the "ka_angular" field.</summary>
    public const int KaAngularFieldNumber = 4;
    private double kaAngular_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double KaAngular {
      get { return kaAngular_; }
      set {
        kaAngular_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufDifferentialDriveFeedforward);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufDifferentialDriveFeedforward other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(KvLinear, other.KvLinear)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(KaLinear, other.KaLinear)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(KvAngular, other.KvAngular)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(KaAngular, other.KaAngular)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (KvLinear != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(KvLinear);
      if (KaLinear != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(KaLinear);
      if (KvAngular != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(KvAngular);
      if (KaAngular != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(KaAngular);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (KvLinear != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(KvLinear);
      }
      if (KaLinear != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(KaLinear);
      }
      if (KvAngular != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(KvAngular);
      }
      if (KaAngular != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(KaAngular);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (KvLinear != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(KvLinear);
      }
      if (KaLinear != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(KaLinear);
      }
      if (KvAngular != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(KvAngular);
      }
      if (KaAngular != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(KaAngular);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (KvLinear != 0D) {
        size += 1 + 8;
      }
      if (KaLinear != 0D) {
        size += 1 + 8;
      }
      if (KvAngular != 0D) {
        size += 1 + 8;
      }
      if (KaAngular != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufDifferentialDriveFeedforward other) {
      if (other == null) {
        return;
      }
      if (other.KvLinear != 0D) {
        KvLinear = other.KvLinear;
      }
      if (other.KaLinear != 0D) {
        KaLinear = other.KaLinear;
      }
      if (other.KvAngular != 0D) {
        KvAngular = other.KvAngular;
      }
      if (other.KaAngular != 0D) {
        KaAngular = other.KaAngular;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            KvLinear = input.ReadDouble();
            break;
          }
          case 17: {
            KaLinear = input.ReadDouble();
            break;
          }
          case 25: {
            KvAngular = input.ReadDouble();
            break;
          }
          case 33: {
            KaAngular = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            KvLinear = input.ReadDouble();
            break;
          }
          case 17: {
            KaLinear = input.ReadDouble();
            break;
          }
          case 25: {
            KvAngular = input.ReadDouble();
            break;
          }
          case 33: {
            KaAngular = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufElevatorFeedforward : pb::IMessage<ProtobufElevatorFeedforward>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufElevatorFeedforward> _parser = new pb::MessageParser<ProtobufElevatorFeedforward>(() => new ProtobufElevatorFeedforward());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufElevatorFeedforward> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.ControllerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufElevatorFeedforward() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufElevatorFeedforward(ProtobufElevatorFeedforward other) : this() {
      ks_ = other.ks_;
      kg_ = other.kg_;
      kv_ = other.kv_;
      ka_ = other.ka_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufElevatorFeedforward Clone() {
      return new ProtobufElevatorFeedforward(this);
    }

    /// <summary>Field number for the "ks" field.</summary>
    public const int KsFieldNumber = 1;
    private double ks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Ks {
      get { return ks_; }
      set {
        ks_ = value;
      }
    }

    /// <summary>Field number for the "kg" field.</summary>
    public const int KgFieldNumber = 2;
    private double kg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Kg {
      get { return kg_; }
      set {
        kg_ = value;
      }
    }

    /// <summary>Field number for the "kv" field.</summary>
    public const int KvFieldNumber = 3;
    private double kv_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Kv {
      get { return kv_; }
      set {
        kv_ = value;
      }
    }

    /// <summary>Field number for the "ka" field.</summary>
    public const int KaFieldNumber = 4;
    private double ka_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Ka {
      get { return ka_; }
      set {
        ka_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufElevatorFeedforward);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufElevatorFeedforward other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Ks, other.Ks)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Kg, other.Kg)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Kv, other.Kv)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Ka, other.Ka)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ks != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Ks);
      if (Kg != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Kg);
      if (Kv != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Kv);
      if (Ka != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Ka);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ks != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Ks);
      }
      if (Kg != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Kg);
      }
      if (Kv != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Kv);
      }
      if (Ka != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Ka);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ks != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Ks);
      }
      if (Kg != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Kg);
      }
      if (Kv != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Kv);
      }
      if (Ka != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(Ka);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ks != 0D) {
        size += 1 + 8;
      }
      if (Kg != 0D) {
        size += 1 + 8;
      }
      if (Kv != 0D) {
        size += 1 + 8;
      }
      if (Ka != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufElevatorFeedforward other) {
      if (other == null) {
        return;
      }
      if (other.Ks != 0D) {
        Ks = other.Ks;
      }
      if (other.Kg != 0D) {
        Kg = other.Kg;
      }
      if (other.Kv != 0D) {
        Kv = other.Kv;
      }
      if (other.Ka != 0D) {
        Ka = other.Ka;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Ks = input.ReadDouble();
            break;
          }
          case 17: {
            Kg = input.ReadDouble();
            break;
          }
          case 25: {
            Kv = input.ReadDouble();
            break;
          }
          case 33: {
            Ka = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Ks = input.ReadDouble();
            break;
          }
          case 17: {
            Kg = input.ReadDouble();
            break;
          }
          case 25: {
            Kv = input.ReadDouble();
            break;
          }
          case 33: {
            Ka = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufSimpleMotorFeedforward : pb::IMessage<ProtobufSimpleMotorFeedforward>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufSimpleMotorFeedforward> _parser = new pb::MessageParser<ProtobufSimpleMotorFeedforward>(() => new ProtobufSimpleMotorFeedforward());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufSimpleMotorFeedforward> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.ControllerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSimpleMotorFeedforward() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSimpleMotorFeedforward(ProtobufSimpleMotorFeedforward other) : this() {
      ks_ = other.ks_;
      kv_ = other.kv_;
      ka_ = other.ka_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSimpleMotorFeedforward Clone() {
      return new ProtobufSimpleMotorFeedforward(this);
    }

    /// <summary>Field number for the "ks" field.</summary>
    public const int KsFieldNumber = 1;
    private double ks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Ks {
      get { return ks_; }
      set {
        ks_ = value;
      }
    }

    /// <summary>Field number for the "kv" field.</summary>
    public const int KvFieldNumber = 2;
    private double kv_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Kv {
      get { return kv_; }
      set {
        kv_ = value;
      }
    }

    /// <summary>Field number for the "ka" field.</summary>
    public const int KaFieldNumber = 3;
    private double ka_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Ka {
      get { return ka_; }
      set {
        ka_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufSimpleMotorFeedforward);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufSimpleMotorFeedforward other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Ks, other.Ks)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Kv, other.Kv)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Ka, other.Ka)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ks != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Ks);
      if (Kv != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Kv);
      if (Ka != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Ka);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ks != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Ks);
      }
      if (Kv != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Kv);
      }
      if (Ka != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Ka);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ks != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Ks);
      }
      if (Kv != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Kv);
      }
      if (Ka != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Ka);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ks != 0D) {
        size += 1 + 8;
      }
      if (Kv != 0D) {
        size += 1 + 8;
      }
      if (Ka != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufSimpleMotorFeedforward other) {
      if (other == null) {
        return;
      }
      if (other.Ks != 0D) {
        Ks = other.Ks;
      }
      if (other.Kv != 0D) {
        Kv = other.Kv;
      }
      if (other.Ka != 0D) {
        Ka = other.Ka;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Ks = input.ReadDouble();
            break;
          }
          case 17: {
            Kv = input.ReadDouble();
            break;
          }
          case 25: {
            Ka = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Ks = input.ReadDouble();
            break;
          }
          case 17: {
            Kv = input.ReadDouble();
            break;
          }
          case 25: {
            Ka = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufDifferentialDriveWheelVoltages : pb::IMessage<ProtobufDifferentialDriveWheelVoltages>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufDifferentialDriveWheelVoltages> _parser = new pb::MessageParser<ProtobufDifferentialDriveWheelVoltages>(() => new ProtobufDifferentialDriveWheelVoltages());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufDifferentialDriveWheelVoltages> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.ControllerReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveWheelVoltages() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveWheelVoltages(ProtobufDifferentialDriveWheelVoltages other) : this() {
      left_ = other.left_;
      right_ = other.right_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveWheelVoltages Clone() {
      return new ProtobufDifferentialDriveWheelVoltages(this);
    }

    /// <summary>Field number for the "left" field.</summary>
    public const int LeftFieldNumber = 1;
    private double left_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Left {
      get { return left_; }
      set {
        left_ = value;
      }
    }

    /// <summary>Field number for the "right" field.</summary>
    public const int RightFieldNumber = 2;
    private double right_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Right {
      get { return right_; }
      set {
        right_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufDifferentialDriveWheelVoltages);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufDifferentialDriveWheelVoltages other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Left, other.Left)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Right, other.Right)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Left != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Left);
      if (Right != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Right);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Left != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Left);
      }
      if (Right != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Right);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Left != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Left);
      }
      if (Right != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Right);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Left != 0D) {
        size += 1 + 8;
      }
      if (Right != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufDifferentialDriveWheelVoltages other) {
      if (other == null) {
        return;
      }
      if (other.Left != 0D) {
        Left = other.Left;
      }
      if (other.Right != 0D) {
        Right = other.Right;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Left = input.ReadDouble();
            break;
          }
          case 17: {
            Right = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Left = input.ReadDouble();
            break;
          }
          case 17: {
            Right = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
