// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: kinematics.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WPIMath.Proto {

  /// <summary>Holder for reflection information generated from kinematics.proto</summary>
  public static partial class KinematicsReflection {

    #region Descriptor
    /// <summary>File descriptor for kinematics.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KinematicsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBraW5lbWF0aWNzLnByb3RvEgl3cGkucHJvdG8aEGdlb21ldHJ5MmQucHJv",
            "dG8iPgoVUHJvdG9idWZDaGFzc2lzU3BlZWRzEgoKAnZ4GAEgASgBEgoKAnZ5",
            "GAIgASgBEg0KBW9tZWdhGAMgASgBIjoKI1Byb3RvYnVmRGlmZmVyZW50aWFs",
            "RHJpdmVLaW5lbWF0aWNzEhMKC3RyYWNrX3dpZHRoGAEgASgBIkMKJFByb3Rv",
            "YnVmRGlmZmVyZW50aWFsRHJpdmVXaGVlbFNwZWVkcxIMCgRsZWZ0GAEgASgB",
            "Eg0KBXJpZ2h0GAIgASgBIvgBCh5Qcm90b2J1Zk1lY2FudW1Ecml2ZUtpbmVt",
            "YXRpY3MSNAoKZnJvbnRfbGVmdBgBIAEoCzIgLndwaS5wcm90by5Qcm90b2J1",
            "ZlRyYW5zbGF0aW9uMmQSNQoLZnJvbnRfcmlnaHQYAiABKAsyIC53cGkucHJv",
            "dG8uUHJvdG9idWZUcmFuc2xhdGlvbjJkEjMKCXJlYXJfbGVmdBgDIAEoCzIg",
            "LndwaS5wcm90by5Qcm90b2J1ZlRyYW5zbGF0aW9uMmQSNAoKcmVhcl9yaWdo",
            "dBgEIAEoCzIgLndwaS5wcm90by5Qcm90b2J1ZlRyYW5zbGF0aW9uMmQicwoh",
            "UHJvdG9idWZNZWNhbnVtRHJpdmVNb3RvclZvbHRhZ2VzEhIKCmZyb250X2xl",
            "ZnQYASABKAESEwoLZnJvbnRfcmlnaHQYAiABKAESEQoJcmVhcl9sZWZ0GAMg",
            "ASgBEhIKCnJlYXJfcmlnaHQYBCABKAEidAoiUHJvdG9idWZNZWNhbnVtRHJp",
            "dmVXaGVlbFBvc2l0aW9ucxISCgpmcm9udF9sZWZ0GAEgASgBEhMKC2Zyb250",
            "X3JpZ2h0GAIgASgBEhEKCXJlYXJfbGVmdBgDIAEoARISCgpyZWFyX3JpZ2h0",
            "GAQgASgBInEKH1Byb3RvYnVmTWVjYW51bURyaXZlV2hlZWxTcGVlZHMSEgoK",
            "ZnJvbnRfbGVmdBgBIAEoARITCgtmcm9udF9yaWdodBgCIAEoARIRCglyZWFy",
            "X2xlZnQYAyABKAESEgoKcmVhcl9yaWdodBgEIAEoASJSCh1Qcm90b2J1ZlN3",
            "ZXJ2ZURyaXZlS2luZW1hdGljcxIxCgdtb2R1bGVzGAEgAygLMiAud3BpLnBy",
            "b3RvLlByb3RvYnVmVHJhbnNsYXRpb24yZCJeChxQcm90b2J1ZlN3ZXJ2ZU1v",
            "ZHVsZVBvc2l0aW9uEhAKCGRpc3RhbmNlGAEgASgBEiwKBWFuZ2xlGAIgASgL",
            "Mh0ud3BpLnByb3RvLlByb3RvYnVmUm90YXRpb24yZCJYChlQcm90b2J1ZlN3",
            "ZXJ2ZU1vZHVsZVN0YXRlEg0KBXNwZWVkGAEgASgBEiwKBWFuZ2xlGAIgASgL",
            "Mh0ud3BpLnByb3RvLlByb3RvYnVmUm90YXRpb24yZEIqChhlZHUud3BpLmZp",
            "cnN0Lm1hdGgucHJvdG+qAg1XUElNYXRoLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WPIMath.Proto.Geometry2DReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufChassisSpeeds), global::WPIMath.Proto.ProtobufChassisSpeeds.Parser, new[]{ "Vx", "Vy", "Omega" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufDifferentialDriveKinematics), global::WPIMath.Proto.ProtobufDifferentialDriveKinematics.Parser, new[]{ "TrackWidth" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufDifferentialDriveWheelSpeeds), global::WPIMath.Proto.ProtobufDifferentialDriveWheelSpeeds.Parser, new[]{ "Left", "Right" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufMecanumDriveKinematics), global::WPIMath.Proto.ProtobufMecanumDriveKinematics.Parser, new[]{ "FrontLeft", "FrontRight", "RearLeft", "RearRight" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufMecanumDriveMotorVoltages), global::WPIMath.Proto.ProtobufMecanumDriveMotorVoltages.Parser, new[]{ "FrontLeft", "FrontRight", "RearLeft", "RearRight" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufMecanumDriveWheelPositions), global::WPIMath.Proto.ProtobufMecanumDriveWheelPositions.Parser, new[]{ "FrontLeft", "FrontRight", "RearLeft", "RearRight" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufMecanumDriveWheelSpeeds), global::WPIMath.Proto.ProtobufMecanumDriveWheelSpeeds.Parser, new[]{ "FrontLeft", "FrontRight", "RearLeft", "RearRight" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufSwerveDriveKinematics), global::WPIMath.Proto.ProtobufSwerveDriveKinematics.Parser, new[]{ "Modules" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufSwerveModulePosition), global::WPIMath.Proto.ProtobufSwerveModulePosition.Parser, new[]{ "Distance", "Angle" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufSwerveModuleState), global::WPIMath.Proto.ProtobufSwerveModuleState.Parser, new[]{ "Speed", "Angle" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtobufChassisSpeeds : pb::IMessage<ProtobufChassisSpeeds>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufChassisSpeeds> _parser = new pb::MessageParser<ProtobufChassisSpeeds>(() => new ProtobufChassisSpeeds());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufChassisSpeeds> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.KinematicsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufChassisSpeeds() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufChassisSpeeds(ProtobufChassisSpeeds other) : this() {
      vx_ = other.vx_;
      vy_ = other.vy_;
      omega_ = other.omega_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufChassisSpeeds Clone() {
      return new ProtobufChassisSpeeds(this);
    }

    /// <summary>Field number for the "vx" field.</summary>
    public const int VxFieldNumber = 1;
    private double vx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Vx {
      get { return vx_; }
      set {
        vx_ = value;
      }
    }

    /// <summary>Field number for the "vy" field.</summary>
    public const int VyFieldNumber = 2;
    private double vy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Vy {
      get { return vy_; }
      set {
        vy_ = value;
      }
    }

    /// <summary>Field number for the "omega" field.</summary>
    public const int OmegaFieldNumber = 3;
    private double omega_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Omega {
      get { return omega_; }
      set {
        omega_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufChassisSpeeds);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufChassisSpeeds other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Vx, other.Vx)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Vy, other.Vy)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Omega, other.Omega)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Vx != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Vx);
      if (Vy != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Vy);
      if (Omega != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Omega);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Vx != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Vx);
      }
      if (Vy != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Vy);
      }
      if (Omega != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Omega);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Vx != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Vx);
      }
      if (Vy != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Vy);
      }
      if (Omega != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Omega);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Vx != 0D) {
        size += 1 + 8;
      }
      if (Vy != 0D) {
        size += 1 + 8;
      }
      if (Omega != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufChassisSpeeds other) {
      if (other == null) {
        return;
      }
      if (other.Vx != 0D) {
        Vx = other.Vx;
      }
      if (other.Vy != 0D) {
        Vy = other.Vy;
      }
      if (other.Omega != 0D) {
        Omega = other.Omega;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Vx = input.ReadDouble();
            break;
          }
          case 17: {
            Vy = input.ReadDouble();
            break;
          }
          case 25: {
            Omega = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Vx = input.ReadDouble();
            break;
          }
          case 17: {
            Vy = input.ReadDouble();
            break;
          }
          case 25: {
            Omega = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufDifferentialDriveKinematics : pb::IMessage<ProtobufDifferentialDriveKinematics>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufDifferentialDriveKinematics> _parser = new pb::MessageParser<ProtobufDifferentialDriveKinematics>(() => new ProtobufDifferentialDriveKinematics());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufDifferentialDriveKinematics> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.KinematicsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveKinematics() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveKinematics(ProtobufDifferentialDriveKinematics other) : this() {
      trackWidth_ = other.trackWidth_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveKinematics Clone() {
      return new ProtobufDifferentialDriveKinematics(this);
    }

    /// <summary>Field number for the "track_width" field.</summary>
    public const int TrackWidthFieldNumber = 1;
    private double trackWidth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TrackWidth {
      get { return trackWidth_; }
      set {
        trackWidth_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufDifferentialDriveKinematics);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufDifferentialDriveKinematics other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TrackWidth, other.TrackWidth)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TrackWidth != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TrackWidth);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TrackWidth != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(TrackWidth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TrackWidth != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(TrackWidth);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TrackWidth != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufDifferentialDriveKinematics other) {
      if (other == null) {
        return;
      }
      if (other.TrackWidth != 0D) {
        TrackWidth = other.TrackWidth;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            TrackWidth = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            TrackWidth = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufDifferentialDriveWheelSpeeds : pb::IMessage<ProtobufDifferentialDriveWheelSpeeds>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufDifferentialDriveWheelSpeeds> _parser = new pb::MessageParser<ProtobufDifferentialDriveWheelSpeeds>(() => new ProtobufDifferentialDriveWheelSpeeds());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufDifferentialDriveWheelSpeeds> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.KinematicsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveWheelSpeeds() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveWheelSpeeds(ProtobufDifferentialDriveWheelSpeeds other) : this() {
      left_ = other.left_;
      right_ = other.right_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDifferentialDriveWheelSpeeds Clone() {
      return new ProtobufDifferentialDriveWheelSpeeds(this);
    }

    /// <summary>Field number for the "left" field.</summary>
    public const int LeftFieldNumber = 1;
    private double left_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Left {
      get { return left_; }
      set {
        left_ = value;
      }
    }

    /// <summary>Field number for the "right" field.</summary>
    public const int RightFieldNumber = 2;
    private double right_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Right {
      get { return right_; }
      set {
        right_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufDifferentialDriveWheelSpeeds);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufDifferentialDriveWheelSpeeds other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Left, other.Left)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Right, other.Right)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Left != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Left);
      if (Right != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Right);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Left != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Left);
      }
      if (Right != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Right);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Left != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Left);
      }
      if (Right != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(Right);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Left != 0D) {
        size += 1 + 8;
      }
      if (Right != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufDifferentialDriveWheelSpeeds other) {
      if (other == null) {
        return;
      }
      if (other.Left != 0D) {
        Left = other.Left;
      }
      if (other.Right != 0D) {
        Right = other.Right;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Left = input.ReadDouble();
            break;
          }
          case 17: {
            Right = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Left = input.ReadDouble();
            break;
          }
          case 17: {
            Right = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufMecanumDriveKinematics : pb::IMessage<ProtobufMecanumDriveKinematics>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufMecanumDriveKinematics> _parser = new pb::MessageParser<ProtobufMecanumDriveKinematics>(() => new ProtobufMecanumDriveKinematics());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufMecanumDriveKinematics> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.KinematicsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveKinematics() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveKinematics(ProtobufMecanumDriveKinematics other) : this() {
      frontLeft_ = other.frontLeft_ != null ? other.frontLeft_.Clone() : null;
      frontRight_ = other.frontRight_ != null ? other.frontRight_.Clone() : null;
      rearLeft_ = other.rearLeft_ != null ? other.rearLeft_.Clone() : null;
      rearRight_ = other.rearRight_ != null ? other.rearRight_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveKinematics Clone() {
      return new ProtobufMecanumDriveKinematics(this);
    }

    /// <summary>Field number for the "front_left" field.</summary>
    public const int FrontLeftFieldNumber = 1;
    private global::WPIMath.Proto.ProtobufTranslation2d frontLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WPIMath.Proto.ProtobufTranslation2d FrontLeft {
      get { return frontLeft_; }
      set {
        frontLeft_ = value;
      }
    }

    /// <summary>Field number for the "front_right" field.</summary>
    public const int FrontRightFieldNumber = 2;
    private global::WPIMath.Proto.ProtobufTranslation2d frontRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WPIMath.Proto.ProtobufTranslation2d FrontRight {
      get { return frontRight_; }
      set {
        frontRight_ = value;
      }
    }

    /// <summary>Field number for the "rear_left" field.</summary>
    public const int RearLeftFieldNumber = 3;
    private global::WPIMath.Proto.ProtobufTranslation2d rearLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WPIMath.Proto.ProtobufTranslation2d RearLeft {
      get { return rearLeft_; }
      set {
        rearLeft_ = value;
      }
    }

    /// <summary>Field number for the "rear_right" field.</summary>
    public const int RearRightFieldNumber = 4;
    private global::WPIMath.Proto.ProtobufTranslation2d rearRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WPIMath.Proto.ProtobufTranslation2d RearRight {
      get { return rearRight_; }
      set {
        rearRight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufMecanumDriveKinematics);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufMecanumDriveKinematics other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FrontLeft, other.FrontLeft)) return false;
      if (!object.Equals(FrontRight, other.FrontRight)) return false;
      if (!object.Equals(RearLeft, other.RearLeft)) return false;
      if (!object.Equals(RearRight, other.RearRight)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (frontLeft_ != null) hash ^= FrontLeft.GetHashCode();
      if (frontRight_ != null) hash ^= FrontRight.GetHashCode();
      if (rearLeft_ != null) hash ^= RearLeft.GetHashCode();
      if (rearRight_ != null) hash ^= RearRight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (frontLeft_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FrontLeft);
      }
      if (frontRight_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FrontRight);
      }
      if (rearLeft_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RearLeft);
      }
      if (rearRight_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(RearRight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (frontLeft_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FrontLeft);
      }
      if (frontRight_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FrontRight);
      }
      if (rearLeft_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RearLeft);
      }
      if (rearRight_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(RearRight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (frontLeft_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FrontLeft);
      }
      if (frontRight_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FrontRight);
      }
      if (rearLeft_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RearLeft);
      }
      if (rearRight_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RearRight);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufMecanumDriveKinematics other) {
      if (other == null) {
        return;
      }
      if (other.frontLeft_ != null) {
        if (frontLeft_ == null) {
          FrontLeft = new global::WPIMath.Proto.ProtobufTranslation2d();
        }
        FrontLeft.MergeFrom(other.FrontLeft);
      }
      if (other.frontRight_ != null) {
        if (frontRight_ == null) {
          FrontRight = new global::WPIMath.Proto.ProtobufTranslation2d();
        }
        FrontRight.MergeFrom(other.FrontRight);
      }
      if (other.rearLeft_ != null) {
        if (rearLeft_ == null) {
          RearLeft = new global::WPIMath.Proto.ProtobufTranslation2d();
        }
        RearLeft.MergeFrom(other.RearLeft);
      }
      if (other.rearRight_ != null) {
        if (rearRight_ == null) {
          RearRight = new global::WPIMath.Proto.ProtobufTranslation2d();
        }
        RearRight.MergeFrom(other.RearRight);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (frontLeft_ == null) {
              FrontLeft = new global::WPIMath.Proto.ProtobufTranslation2d();
            }
            input.ReadMessage(FrontLeft);
            break;
          }
          case 18: {
            if (frontRight_ == null) {
              FrontRight = new global::WPIMath.Proto.ProtobufTranslation2d();
            }
            input.ReadMessage(FrontRight);
            break;
          }
          case 26: {
            if (rearLeft_ == null) {
              RearLeft = new global::WPIMath.Proto.ProtobufTranslation2d();
            }
            input.ReadMessage(RearLeft);
            break;
          }
          case 34: {
            if (rearRight_ == null) {
              RearRight = new global::WPIMath.Proto.ProtobufTranslation2d();
            }
            input.ReadMessage(RearRight);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (frontLeft_ == null) {
              FrontLeft = new global::WPIMath.Proto.ProtobufTranslation2d();
            }
            input.ReadMessage(FrontLeft);
            break;
          }
          case 18: {
            if (frontRight_ == null) {
              FrontRight = new global::WPIMath.Proto.ProtobufTranslation2d();
            }
            input.ReadMessage(FrontRight);
            break;
          }
          case 26: {
            if (rearLeft_ == null) {
              RearLeft = new global::WPIMath.Proto.ProtobufTranslation2d();
            }
            input.ReadMessage(RearLeft);
            break;
          }
          case 34: {
            if (rearRight_ == null) {
              RearRight = new global::WPIMath.Proto.ProtobufTranslation2d();
            }
            input.ReadMessage(RearRight);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufMecanumDriveMotorVoltages : pb::IMessage<ProtobufMecanumDriveMotorVoltages>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufMecanumDriveMotorVoltages> _parser = new pb::MessageParser<ProtobufMecanumDriveMotorVoltages>(() => new ProtobufMecanumDriveMotorVoltages());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufMecanumDriveMotorVoltages> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.KinematicsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveMotorVoltages() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveMotorVoltages(ProtobufMecanumDriveMotorVoltages other) : this() {
      frontLeft_ = other.frontLeft_;
      frontRight_ = other.frontRight_;
      rearLeft_ = other.rearLeft_;
      rearRight_ = other.rearRight_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveMotorVoltages Clone() {
      return new ProtobufMecanumDriveMotorVoltages(this);
    }

    /// <summary>Field number for the "front_left" field.</summary>
    public const int FrontLeftFieldNumber = 1;
    private double frontLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double FrontLeft {
      get { return frontLeft_; }
      set {
        frontLeft_ = value;
      }
    }

    /// <summary>Field number for the "front_right" field.</summary>
    public const int FrontRightFieldNumber = 2;
    private double frontRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double FrontRight {
      get { return frontRight_; }
      set {
        frontRight_ = value;
      }
    }

    /// <summary>Field number for the "rear_left" field.</summary>
    public const int RearLeftFieldNumber = 3;
    private double rearLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double RearLeft {
      get { return rearLeft_; }
      set {
        rearLeft_ = value;
      }
    }

    /// <summary>Field number for the "rear_right" field.</summary>
    public const int RearRightFieldNumber = 4;
    private double rearRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double RearRight {
      get { return rearRight_; }
      set {
        rearRight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufMecanumDriveMotorVoltages);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufMecanumDriveMotorVoltages other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FrontLeft, other.FrontLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FrontRight, other.FrontRight)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(RearLeft, other.RearLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(RearRight, other.RearRight)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FrontLeft != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FrontLeft);
      if (FrontRight != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FrontRight);
      if (RearLeft != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(RearLeft);
      if (RearRight != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(RearRight);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrontLeft != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(FrontLeft);
      }
      if (FrontRight != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(FrontRight);
      }
      if (RearLeft != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(RearLeft);
      }
      if (RearRight != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(RearRight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrontLeft != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(FrontLeft);
      }
      if (FrontRight != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(FrontRight);
      }
      if (RearLeft != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(RearLeft);
      }
      if (RearRight != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(RearRight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FrontLeft != 0D) {
        size += 1 + 8;
      }
      if (FrontRight != 0D) {
        size += 1 + 8;
      }
      if (RearLeft != 0D) {
        size += 1 + 8;
      }
      if (RearRight != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufMecanumDriveMotorVoltages other) {
      if (other == null) {
        return;
      }
      if (other.FrontLeft != 0D) {
        FrontLeft = other.FrontLeft;
      }
      if (other.FrontRight != 0D) {
        FrontRight = other.FrontRight;
      }
      if (other.RearLeft != 0D) {
        RearLeft = other.RearLeft;
      }
      if (other.RearRight != 0D) {
        RearRight = other.RearRight;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            FrontLeft = input.ReadDouble();
            break;
          }
          case 17: {
            FrontRight = input.ReadDouble();
            break;
          }
          case 25: {
            RearLeft = input.ReadDouble();
            break;
          }
          case 33: {
            RearRight = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            FrontLeft = input.ReadDouble();
            break;
          }
          case 17: {
            FrontRight = input.ReadDouble();
            break;
          }
          case 25: {
            RearLeft = input.ReadDouble();
            break;
          }
          case 33: {
            RearRight = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufMecanumDriveWheelPositions : pb::IMessage<ProtobufMecanumDriveWheelPositions>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufMecanumDriveWheelPositions> _parser = new pb::MessageParser<ProtobufMecanumDriveWheelPositions>(() => new ProtobufMecanumDriveWheelPositions());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufMecanumDriveWheelPositions> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.KinematicsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveWheelPositions() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveWheelPositions(ProtobufMecanumDriveWheelPositions other) : this() {
      frontLeft_ = other.frontLeft_;
      frontRight_ = other.frontRight_;
      rearLeft_ = other.rearLeft_;
      rearRight_ = other.rearRight_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveWheelPositions Clone() {
      return new ProtobufMecanumDriveWheelPositions(this);
    }

    /// <summary>Field number for the "front_left" field.</summary>
    public const int FrontLeftFieldNumber = 1;
    private double frontLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double FrontLeft {
      get { return frontLeft_; }
      set {
        frontLeft_ = value;
      }
    }

    /// <summary>Field number for the "front_right" field.</summary>
    public const int FrontRightFieldNumber = 2;
    private double frontRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double FrontRight {
      get { return frontRight_; }
      set {
        frontRight_ = value;
      }
    }

    /// <summary>Field number for the "rear_left" field.</summary>
    public const int RearLeftFieldNumber = 3;
    private double rearLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double RearLeft {
      get { return rearLeft_; }
      set {
        rearLeft_ = value;
      }
    }

    /// <summary>Field number for the "rear_right" field.</summary>
    public const int RearRightFieldNumber = 4;
    private double rearRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double RearRight {
      get { return rearRight_; }
      set {
        rearRight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufMecanumDriveWheelPositions);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufMecanumDriveWheelPositions other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FrontLeft, other.FrontLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FrontRight, other.FrontRight)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(RearLeft, other.RearLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(RearRight, other.RearRight)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FrontLeft != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FrontLeft);
      if (FrontRight != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FrontRight);
      if (RearLeft != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(RearLeft);
      if (RearRight != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(RearRight);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrontLeft != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(FrontLeft);
      }
      if (FrontRight != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(FrontRight);
      }
      if (RearLeft != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(RearLeft);
      }
      if (RearRight != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(RearRight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrontLeft != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(FrontLeft);
      }
      if (FrontRight != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(FrontRight);
      }
      if (RearLeft != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(RearLeft);
      }
      if (RearRight != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(RearRight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FrontLeft != 0D) {
        size += 1 + 8;
      }
      if (FrontRight != 0D) {
        size += 1 + 8;
      }
      if (RearLeft != 0D) {
        size += 1 + 8;
      }
      if (RearRight != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufMecanumDriveWheelPositions other) {
      if (other == null) {
        return;
      }
      if (other.FrontLeft != 0D) {
        FrontLeft = other.FrontLeft;
      }
      if (other.FrontRight != 0D) {
        FrontRight = other.FrontRight;
      }
      if (other.RearLeft != 0D) {
        RearLeft = other.RearLeft;
      }
      if (other.RearRight != 0D) {
        RearRight = other.RearRight;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            FrontLeft = input.ReadDouble();
            break;
          }
          case 17: {
            FrontRight = input.ReadDouble();
            break;
          }
          case 25: {
            RearLeft = input.ReadDouble();
            break;
          }
          case 33: {
            RearRight = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            FrontLeft = input.ReadDouble();
            break;
          }
          case 17: {
            FrontRight = input.ReadDouble();
            break;
          }
          case 25: {
            RearLeft = input.ReadDouble();
            break;
          }
          case 33: {
            RearRight = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufMecanumDriveWheelSpeeds : pb::IMessage<ProtobufMecanumDriveWheelSpeeds>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufMecanumDriveWheelSpeeds> _parser = new pb::MessageParser<ProtobufMecanumDriveWheelSpeeds>(() => new ProtobufMecanumDriveWheelSpeeds());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufMecanumDriveWheelSpeeds> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.KinematicsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveWheelSpeeds() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveWheelSpeeds(ProtobufMecanumDriveWheelSpeeds other) : this() {
      frontLeft_ = other.frontLeft_;
      frontRight_ = other.frontRight_;
      rearLeft_ = other.rearLeft_;
      rearRight_ = other.rearRight_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufMecanumDriveWheelSpeeds Clone() {
      return new ProtobufMecanumDriveWheelSpeeds(this);
    }

    /// <summary>Field number for the "front_left" field.</summary>
    public const int FrontLeftFieldNumber = 1;
    private double frontLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double FrontLeft {
      get { return frontLeft_; }
      set {
        frontLeft_ = value;
      }
    }

    /// <summary>Field number for the "front_right" field.</summary>
    public const int FrontRightFieldNumber = 2;
    private double frontRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double FrontRight {
      get { return frontRight_; }
      set {
        frontRight_ = value;
      }
    }

    /// <summary>Field number for the "rear_left" field.</summary>
    public const int RearLeftFieldNumber = 3;
    private double rearLeft_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double RearLeft {
      get { return rearLeft_; }
      set {
        rearLeft_ = value;
      }
    }

    /// <summary>Field number for the "rear_right" field.</summary>
    public const int RearRightFieldNumber = 4;
    private double rearRight_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double RearRight {
      get { return rearRight_; }
      set {
        rearRight_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufMecanumDriveWheelSpeeds);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufMecanumDriveWheelSpeeds other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FrontLeft, other.FrontLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FrontRight, other.FrontRight)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(RearLeft, other.RearLeft)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(RearRight, other.RearRight)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FrontLeft != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FrontLeft);
      if (FrontRight != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FrontRight);
      if (RearLeft != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(RearLeft);
      if (RearRight != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(RearRight);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FrontLeft != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(FrontLeft);
      }
      if (FrontRight != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(FrontRight);
      }
      if (RearLeft != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(RearLeft);
      }
      if (RearRight != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(RearRight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FrontLeft != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(FrontLeft);
      }
      if (FrontRight != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(FrontRight);
      }
      if (RearLeft != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(RearLeft);
      }
      if (RearRight != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(RearRight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FrontLeft != 0D) {
        size += 1 + 8;
      }
      if (FrontRight != 0D) {
        size += 1 + 8;
      }
      if (RearLeft != 0D) {
        size += 1 + 8;
      }
      if (RearRight != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufMecanumDriveWheelSpeeds other) {
      if (other == null) {
        return;
      }
      if (other.FrontLeft != 0D) {
        FrontLeft = other.FrontLeft;
      }
      if (other.FrontRight != 0D) {
        FrontRight = other.FrontRight;
      }
      if (other.RearLeft != 0D) {
        RearLeft = other.RearLeft;
      }
      if (other.RearRight != 0D) {
        RearRight = other.RearRight;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            FrontLeft = input.ReadDouble();
            break;
          }
          case 17: {
            FrontRight = input.ReadDouble();
            break;
          }
          case 25: {
            RearLeft = input.ReadDouble();
            break;
          }
          case 33: {
            RearRight = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            FrontLeft = input.ReadDouble();
            break;
          }
          case 17: {
            FrontRight = input.ReadDouble();
            break;
          }
          case 25: {
            RearLeft = input.ReadDouble();
            break;
          }
          case 33: {
            RearRight = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufSwerveDriveKinematics : pb::IMessage<ProtobufSwerveDriveKinematics>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufSwerveDriveKinematics> _parser = new pb::MessageParser<ProtobufSwerveDriveKinematics>(() => new ProtobufSwerveDriveKinematics());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufSwerveDriveKinematics> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.KinematicsReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSwerveDriveKinematics() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSwerveDriveKinematics(ProtobufSwerveDriveKinematics other) : this() {
      modules_ = other.modules_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSwerveDriveKinematics Clone() {
      return new ProtobufSwerveDriveKinematics(this);
    }

    /// <summary>Field number for the "modules" field.</summary>
    public const int ModulesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::WPIMath.Proto.ProtobufTranslation2d> _repeated_modules_codec
        = pb::FieldCodec.ForMessage(10, global::WPIMath.Proto.ProtobufTranslation2d.Parser);
    private readonly pbc::RepeatedField<global::WPIMath.Proto.ProtobufTranslation2d> modules_ = new pbc::RepeatedField<global::WPIMath.Proto.ProtobufTranslation2d>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::WPIMath.Proto.ProtobufTranslation2d> Modules {
      get { return modules_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufSwerveDriveKinematics);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufSwerveDriveKinematics other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!modules_.Equals(other.modules_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= modules_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      modules_.WriteTo(output, _repeated_modules_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      modules_.WriteTo(ref output, _repeated_modules_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += modules_.CalculateSize(_repeated_modules_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufSwerveDriveKinematics other) {
      if (other == null) {
        return;
      }
      modules_.Add(other.modules_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            modules_.AddEntriesFrom(input, _repeated_modules_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            modules_.AddEntriesFrom(ref input, _repeated_modules_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufSwerveModulePosition : pb::IMessage<ProtobufSwerveModulePosition>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufSwerveModulePosition> _parser = new pb::MessageParser<ProtobufSwerveModulePosition>(() => new ProtobufSwerveModulePosition());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufSwerveModulePosition> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.KinematicsReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSwerveModulePosition() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSwerveModulePosition(ProtobufSwerveModulePosition other) : this() {
      distance_ = other.distance_;
      angle_ = other.angle_ != null ? other.angle_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSwerveModulePosition Clone() {
      return new ProtobufSwerveModulePosition(this);
    }

    /// <summary>Field number for the "distance" field.</summary>
    public const int DistanceFieldNumber = 1;
    private double distance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Distance {
      get { return distance_; }
      set {
        distance_ = value;
      }
    }

    /// <summary>Field number for the "angle" field.</summary>
    public const int AngleFieldNumber = 2;
    private global::WPIMath.Proto.ProtobufRotation2d angle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WPIMath.Proto.ProtobufRotation2d Angle {
      get { return angle_; }
      set {
        angle_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufSwerveModulePosition);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufSwerveModulePosition other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Distance, other.Distance)) return false;
      if (!object.Equals(Angle, other.Angle)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Distance != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Distance);
      if (angle_ != null) hash ^= Angle.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Distance != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Distance);
      }
      if (angle_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Angle);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Distance != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Distance);
      }
      if (angle_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Angle);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Distance != 0D) {
        size += 1 + 8;
      }
      if (angle_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angle);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufSwerveModulePosition other) {
      if (other == null) {
        return;
      }
      if (other.Distance != 0D) {
        Distance = other.Distance;
      }
      if (other.angle_ != null) {
        if (angle_ == null) {
          Angle = new global::WPIMath.Proto.ProtobufRotation2d();
        }
        Angle.MergeFrom(other.Angle);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Distance = input.ReadDouble();
            break;
          }
          case 18: {
            if (angle_ == null) {
              Angle = new global::WPIMath.Proto.ProtobufRotation2d();
            }
            input.ReadMessage(Angle);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Distance = input.ReadDouble();
            break;
          }
          case 18: {
            if (angle_ == null) {
              Angle = new global::WPIMath.Proto.ProtobufRotation2d();
            }
            input.ReadMessage(Angle);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtobufSwerveModuleState : pb::IMessage<ProtobufSwerveModuleState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufSwerveModuleState> _parser = new pb::MessageParser<ProtobufSwerveModuleState>(() => new ProtobufSwerveModuleState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufSwerveModuleState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.KinematicsReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSwerveModuleState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSwerveModuleState(ProtobufSwerveModuleState other) : this() {
      speed_ = other.speed_;
      angle_ = other.angle_ != null ? other.angle_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufSwerveModuleState Clone() {
      return new ProtobufSwerveModuleState(this);
    }

    /// <summary>Field number for the "speed" field.</summary>
    public const int SpeedFieldNumber = 1;
    private double speed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Speed {
      get { return speed_; }
      set {
        speed_ = value;
      }
    }

    /// <summary>Field number for the "angle" field.</summary>
    public const int AngleFieldNumber = 2;
    private global::WPIMath.Proto.ProtobufRotation2d angle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WPIMath.Proto.ProtobufRotation2d Angle {
      get { return angle_; }
      set {
        angle_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufSwerveModuleState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufSwerveModuleState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Speed, other.Speed)) return false;
      if (!object.Equals(Angle, other.Angle)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Speed != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Speed);
      if (angle_ != null) hash ^= Angle.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Speed != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Speed);
      }
      if (angle_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Angle);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Speed != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(Speed);
      }
      if (angle_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Angle);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Speed != 0D) {
        size += 1 + 8;
      }
      if (angle_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angle);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufSwerveModuleState other) {
      if (other == null) {
        return;
      }
      if (other.Speed != 0D) {
        Speed = other.Speed;
      }
      if (other.angle_ != null) {
        if (angle_ == null) {
          Angle = new global::WPIMath.Proto.ProtobufRotation2d();
        }
        Angle.MergeFrom(other.Angle);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            Speed = input.ReadDouble();
            break;
          }
          case 18: {
            if (angle_ == null) {
              Angle = new global::WPIMath.Proto.ProtobufRotation2d();
            }
            input.ReadMessage(Angle);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            Speed = input.ReadDouble();
            break;
          }
          case 18: {
            if (angle_ == null) {
              Angle = new global::WPIMath.Proto.ProtobufRotation2d();
            }
            input.ReadMessage(Angle);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
