// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: plant.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WPIMath.Proto {

  /// <summary>Holder for reflection information generated from plant.proto</summary>
  public static partial class PlantReflection {

    #region Descriptor
    /// <summary>File descriptor for plant.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlantReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtwbGFudC5wcm90bxIJd3BpLnByb3RvIoEBCg9Qcm90b2J1ZkRDTW90b3IS",
            "FwoPbm9taW5hbF92b2x0YWdlGAEgASgBEhQKDHN0YWxsX3RvcnF1ZRgCIAEo",
            "ARIVCg1zdGFsbF9jdXJyZW50GAMgASgBEhQKDGZyZWVfY3VycmVudBgEIAEo",
            "ARISCgpmcmVlX3NwZWVkGAUgASgBQioKGGVkdS53cGkuZmlyc3QubWF0aC5w",
            "cm90b6oCDVdQSU1hdGguUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufDCMotor), global::WPIMath.Proto.ProtobufDCMotor.Parser, new[]{ "NominalVoltage", "StallTorque", "StallCurrent", "FreeCurrent", "FreeSpeed" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtobufDCMotor : pb::IMessage<ProtobufDCMotor>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufDCMotor> _parser = new pb::MessageParser<ProtobufDCMotor>(() => new ProtobufDCMotor());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufDCMotor> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.PlantReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDCMotor() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDCMotor(ProtobufDCMotor other) : this() {
      nominalVoltage_ = other.nominalVoltage_;
      stallTorque_ = other.stallTorque_;
      stallCurrent_ = other.stallCurrent_;
      freeCurrent_ = other.freeCurrent_;
      freeSpeed_ = other.freeSpeed_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufDCMotor Clone() {
      return new ProtobufDCMotor(this);
    }

    /// <summary>Field number for the "nominal_voltage" field.</summary>
    public const int NominalVoltageFieldNumber = 1;
    private double nominalVoltage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double NominalVoltage {
      get { return nominalVoltage_; }
      set {
        nominalVoltage_ = value;
      }
    }

    /// <summary>Field number for the "stall_torque" field.</summary>
    public const int StallTorqueFieldNumber = 2;
    private double stallTorque_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double StallTorque {
      get { return stallTorque_; }
      set {
        stallTorque_ = value;
      }
    }

    /// <summary>Field number for the "stall_current" field.</summary>
    public const int StallCurrentFieldNumber = 3;
    private double stallCurrent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double StallCurrent {
      get { return stallCurrent_; }
      set {
        stallCurrent_ = value;
      }
    }

    /// <summary>Field number for the "free_current" field.</summary>
    public const int FreeCurrentFieldNumber = 4;
    private double freeCurrent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double FreeCurrent {
      get { return freeCurrent_; }
      set {
        freeCurrent_ = value;
      }
    }

    /// <summary>Field number for the "free_speed" field.</summary>
    public const int FreeSpeedFieldNumber = 5;
    private double freeSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double FreeSpeed {
      get { return freeSpeed_; }
      set {
        freeSpeed_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufDCMotor);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufDCMotor other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(NominalVoltage, other.NominalVoltage)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StallTorque, other.StallTorque)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StallCurrent, other.StallCurrent)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FreeCurrent, other.FreeCurrent)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FreeSpeed, other.FreeSpeed)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NominalVoltage != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(NominalVoltage);
      if (StallTorque != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StallTorque);
      if (StallCurrent != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StallCurrent);
      if (FreeCurrent != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FreeCurrent);
      if (FreeSpeed != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FreeSpeed);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NominalVoltage != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(NominalVoltage);
      }
      if (StallTorque != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(StallTorque);
      }
      if (StallCurrent != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(StallCurrent);
      }
      if (FreeCurrent != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(FreeCurrent);
      }
      if (FreeSpeed != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(FreeSpeed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NominalVoltage != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(NominalVoltage);
      }
      if (StallTorque != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(StallTorque);
      }
      if (StallCurrent != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(StallCurrent);
      }
      if (FreeCurrent != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(FreeCurrent);
      }
      if (FreeSpeed != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(FreeSpeed);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NominalVoltage != 0D) {
        size += 1 + 8;
      }
      if (StallTorque != 0D) {
        size += 1 + 8;
      }
      if (StallCurrent != 0D) {
        size += 1 + 8;
      }
      if (FreeCurrent != 0D) {
        size += 1 + 8;
      }
      if (FreeSpeed != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufDCMotor other) {
      if (other == null) {
        return;
      }
      if (other.NominalVoltage != 0D) {
        NominalVoltage = other.NominalVoltage;
      }
      if (other.StallTorque != 0D) {
        StallTorque = other.StallTorque;
      }
      if (other.StallCurrent != 0D) {
        StallCurrent = other.StallCurrent;
      }
      if (other.FreeCurrent != 0D) {
        FreeCurrent = other.FreeCurrent;
      }
      if (other.FreeSpeed != 0D) {
        FreeSpeed = other.FreeSpeed;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            NominalVoltage = input.ReadDouble();
            break;
          }
          case 17: {
            StallTorque = input.ReadDouble();
            break;
          }
          case 25: {
            StallCurrent = input.ReadDouble();
            break;
          }
          case 33: {
            FreeCurrent = input.ReadDouble();
            break;
          }
          case 41: {
            FreeSpeed = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            NominalVoltage = input.ReadDouble();
            break;
          }
          case 17: {
            StallTorque = input.ReadDouble();
            break;
          }
          case 25: {
            StallCurrent = input.ReadDouble();
            break;
          }
          case 33: {
            FreeCurrent = input.ReadDouble();
            break;
          }
          case 41: {
            FreeSpeed = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
