// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: system.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WPIMath.Proto {

  /// <summary>Holder for reflection information generated from system.proto</summary>
  public static partial class SystemReflection {

    #region Descriptor
    /// <summary>File descriptor for system.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SystemReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxzeXN0ZW0ucHJvdG8SCXdwaS5wcm90bxoNd3BpbWF0aC5wcm90byLrAQoU",
            "UHJvdG9idWZMaW5lYXJTeXN0ZW0SEgoKbnVtX3N0YXRlcxgBIAEoDRISCgpu",
            "dW1faW5wdXRzGAIgASgNEhMKC251bV9vdXRwdXRzGAMgASgNEiQKAWEYBCAB",
            "KAsyGS53cGkucHJvdG8uUHJvdG9idWZNYXRyaXgSJAoBYhgFIAEoCzIZLndw",
            "aS5wcm90by5Qcm90b2J1Zk1hdHJpeBIkCgFjGAYgASgLMhkud3BpLnByb3Rv",
            "LlByb3RvYnVmTWF0cml4EiQKAWQYByABKAsyGS53cGkucHJvdG8uUHJvdG9i",
            "dWZNYXRyaXhCKgoYZWR1LndwaS5maXJzdC5tYXRoLnByb3RvqgINV1BJTWF0",
            "aC5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::WPIMath.Proto.WpimathReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WPIMath.Proto.ProtobufLinearSystem), global::WPIMath.Proto.ProtobufLinearSystem.Parser, new[]{ "NumStates", "NumInputs", "NumOutputs", "A", "B", "C", "D" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtobufLinearSystem : pb::IMessage<ProtobufLinearSystem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtobufLinearSystem> _parser = new pb::MessageParser<ProtobufLinearSystem>(() => new ProtobufLinearSystem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtobufLinearSystem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WPIMath.Proto.SystemReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufLinearSystem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufLinearSystem(ProtobufLinearSystem other) : this() {
      numStates_ = other.numStates_;
      numInputs_ = other.numInputs_;
      numOutputs_ = other.numOutputs_;
      a_ = other.a_ != null ? other.a_.Clone() : null;
      b_ = other.b_ != null ? other.b_.Clone() : null;
      c_ = other.c_ != null ? other.c_.Clone() : null;
      d_ = other.d_ != null ? other.d_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtobufLinearSystem Clone() {
      return new ProtobufLinearSystem(this);
    }

    /// <summary>Field number for the "num_states" field.</summary>
    public const int NumStatesFieldNumber = 1;
    private uint numStates_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NumStates {
      get { return numStates_; }
      set {
        numStates_ = value;
      }
    }

    /// <summary>Field number for the "num_inputs" field.</summary>
    public const int NumInputsFieldNumber = 2;
    private uint numInputs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NumInputs {
      get { return numInputs_; }
      set {
        numInputs_ = value;
      }
    }

    /// <summary>Field number for the "num_outputs" field.</summary>
    public const int NumOutputsFieldNumber = 3;
    private uint numOutputs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NumOutputs {
      get { return numOutputs_; }
      set {
        numOutputs_ = value;
      }
    }

    /// <summary>Field number for the "a" field.</summary>
    public const int AFieldNumber = 4;
    private global::WPIMath.Proto.ProtobufMatrix a_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WPIMath.Proto.ProtobufMatrix A {
      get { return a_; }
      set {
        a_ = value;
      }
    }

    /// <summary>Field number for the "b" field.</summary>
    public const int BFieldNumber = 5;
    private global::WPIMath.Proto.ProtobufMatrix b_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WPIMath.Proto.ProtobufMatrix B {
      get { return b_; }
      set {
        b_ = value;
      }
    }

    /// <summary>Field number for the "c" field.</summary>
    public const int CFieldNumber = 6;
    private global::WPIMath.Proto.ProtobufMatrix c_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WPIMath.Proto.ProtobufMatrix C {
      get { return c_; }
      set {
        c_ = value;
      }
    }

    /// <summary>Field number for the "d" field.</summary>
    public const int DFieldNumber = 7;
    private global::WPIMath.Proto.ProtobufMatrix d_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WPIMath.Proto.ProtobufMatrix D {
      get { return d_; }
      set {
        d_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtobufLinearSystem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtobufLinearSystem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumStates != other.NumStates) return false;
      if (NumInputs != other.NumInputs) return false;
      if (NumOutputs != other.NumOutputs) return false;
      if (!object.Equals(A, other.A)) return false;
      if (!object.Equals(B, other.B)) return false;
      if (!object.Equals(C, other.C)) return false;
      if (!object.Equals(D, other.D)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NumStates != 0) hash ^= NumStates.GetHashCode();
      if (NumInputs != 0) hash ^= NumInputs.GetHashCode();
      if (NumOutputs != 0) hash ^= NumOutputs.GetHashCode();
      if (a_ != null) hash ^= A.GetHashCode();
      if (b_ != null) hash ^= B.GetHashCode();
      if (c_ != null) hash ^= C.GetHashCode();
      if (d_ != null) hash ^= D.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NumStates != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(NumStates);
      }
      if (NumInputs != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(NumInputs);
      }
      if (NumOutputs != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(NumOutputs);
      }
      if (a_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(A);
      }
      if (b_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(B);
      }
      if (c_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(C);
      }
      if (d_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(D);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NumStates != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(NumStates);
      }
      if (NumInputs != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(NumInputs);
      }
      if (NumOutputs != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(NumOutputs);
      }
      if (a_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(A);
      }
      if (b_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(B);
      }
      if (c_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(C);
      }
      if (d_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(D);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NumStates != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumStates);
      }
      if (NumInputs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumInputs);
      }
      if (NumOutputs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NumOutputs);
      }
      if (a_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(A);
      }
      if (b_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(B);
      }
      if (c_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(C);
      }
      if (d_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(D);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtobufLinearSystem other) {
      if (other == null) {
        return;
      }
      if (other.NumStates != 0) {
        NumStates = other.NumStates;
      }
      if (other.NumInputs != 0) {
        NumInputs = other.NumInputs;
      }
      if (other.NumOutputs != 0) {
        NumOutputs = other.NumOutputs;
      }
      if (other.a_ != null) {
        if (a_ == null) {
          A = new global::WPIMath.Proto.ProtobufMatrix();
        }
        A.MergeFrom(other.A);
      }
      if (other.b_ != null) {
        if (b_ == null) {
          B = new global::WPIMath.Proto.ProtobufMatrix();
        }
        B.MergeFrom(other.B);
      }
      if (other.c_ != null) {
        if (c_ == null) {
          C = new global::WPIMath.Proto.ProtobufMatrix();
        }
        C.MergeFrom(other.C);
      }
      if (other.d_ != null) {
        if (d_ == null) {
          D = new global::WPIMath.Proto.ProtobufMatrix();
        }
        D.MergeFrom(other.D);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NumStates = input.ReadUInt32();
            break;
          }
          case 16: {
            NumInputs = input.ReadUInt32();
            break;
          }
          case 24: {
            NumOutputs = input.ReadUInt32();
            break;
          }
          case 34: {
            if (a_ == null) {
              A = new global::WPIMath.Proto.ProtobufMatrix();
            }
            input.ReadMessage(A);
            break;
          }
          case 42: {
            if (b_ == null) {
              B = new global::WPIMath.Proto.ProtobufMatrix();
            }
            input.ReadMessage(B);
            break;
          }
          case 50: {
            if (c_ == null) {
              C = new global::WPIMath.Proto.ProtobufMatrix();
            }
            input.ReadMessage(C);
            break;
          }
          case 58: {
            if (d_ == null) {
              D = new global::WPIMath.Proto.ProtobufMatrix();
            }
            input.ReadMessage(D);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NumStates = input.ReadUInt32();
            break;
          }
          case 16: {
            NumInputs = input.ReadUInt32();
            break;
          }
          case 24: {
            NumOutputs = input.ReadUInt32();
            break;
          }
          case 34: {
            if (a_ == null) {
              A = new global::WPIMath.Proto.ProtobufMatrix();
            }
            input.ReadMessage(A);
            break;
          }
          case 42: {
            if (b_ == null) {
              B = new global::WPIMath.Proto.ProtobufMatrix();
            }
            input.ReadMessage(B);
            break;
          }
          case 50: {
            if (c_ == null) {
              C = new global::WPIMath.Proto.ProtobufMatrix();
            }
            input.ReadMessage(C);
            break;
          }
          case 58: {
            if (d_ == null) {
              D = new global::WPIMath.Proto.ProtobufMatrix();
            }
            input.ReadMessage(D);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
