// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// THIS FILE WAS AUTO-GENERATED BY ./ntcore/generate_topics.py. DO NOT MODIFY

namespace NetworkTables;

/** NetworkTables generic subscriber. */
public partial interface IGenericSubscriber : ISubscriber
{
    /**
 * Get the last published value.
 * If no value has been published, returns a value with type NetworkTableType.kUnassigned.
 *
 * @return value
 */
    NetworkTableValue Get();

    /**
     * Get an array of all value changes since the last call to readQueue.
     * Also provides a timestamp for each value.
     *
     * <p>The "poll storage" subscribe option can be used to set the queue
     * depth.
     *
     * @return Array of timestamped values; empty array if no new changes have
     *     been published since the previous call.
     */
    NetworkTableValue[] ReadQueue();
}
