// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

// THIS FILE WAS AUTO-GENERATED BY ./ntcore/generate_topics.py. DO NOT MODIFY

namespace NetworkTables;

/** NetworkTables generic publisher. */
public partial interface IGenericPublisher : IPublisher
{
    bool Set(in RefNetworkTableValue value);

    /**
     * Publish a new value.
     *
     * @param value value to publish
     * @param time timestamp; 0 indicates current NT time should be used
     * @return False if the topic already exists with a different type
     * @throws IllegalArgumentException if the value is not a known type
     */
    bool SetValue<T>(T value, long time);

    bool SetValue<T>(T value);

    bool SetDefault(in RefNetworkTableValue defaultValue);

    /**
     * Sets the entry's value if it does not exist.
     *
     * @param defaultValue the default value to set
     * @return False if the entry exists with a different type
     * @throws IllegalArgumentException if the value is not a known type
     */
    bool SetDefaultValue<T>(T defaultValue);

}
